### ISSUE TITLE
detective-typescript uses an unsupported version of typescript

### ISSUE THREAD

**Issue by luisnaranjo733** [dependents/node-precinct#50]
When I run madge, I get this TS warning
```
WARNING: You are currently running a version of TypeScript which is not officially supported by typescript-eslint-parser.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: ~3.0.1

YOUR TYPESCRIPT VERSION: 3.1.3 
```

I opened [an issue ](https://github.com/eslint/typescript-eslint-parser/issues/528#issuecomment-431524481)on typescript-eslint-parser, and we've found that the reason is that detective-typescript declares a TS version that is slightly higher than what typescript-eslint-parser supports.

We should either downgrade the version here, or work with typescript-eslint-parser to get it to raise its supported version. There's not much different between the two versions, they may just need to verify that this version works.

**Comment by mrjoelkemp** [comment]
Hey @luisnaranjo733! Thanks for reporting. I had some hassles wrangling an appropriate version of typescript to get the warnings to go away in our test suite.

Though I agree that this could/should be resolved upstream, I'm reluctant to downgrade here unless there's a clear breakage due to the version discrepancy (which I wouldn't expect since 3.1.3 is a minor and few patches away from the "supported" version).
 
I'd appreciate the help in working with upstream folks to get this squared away. Until then, this seems like a wontfix. 

I'm happy to continue the discussion around this if there's a functional issue that I'm missing.

Thanks again for contributing.
